### ISSUE TITLE
Loot logger showing Incorrect items looted/ Wrong weapons on dps tracker

### ISSUE THREAD

**Issue by Mousey97** [Triky313/AlbionOnline-StatisticsAnalysis#243]
Experiencing an odd problem the past couple weeks where the loot logger is showing incorrect things being looted. For example i looted a 4.3 hallowfall but the logger says 8.1 holy 1h holy staff. I have seen untradeable victory reward pouches from arena show up, as well as many other falsely labeled items that were never looted (but seem to be taking the place of items that WERE looted).

In addition, when viewing the DPS meter it seems to be showing incorrect weapons. I.E. i used an icicle staff 6.3 and it says its an 8.4 permafrost orb on the tracker.

I'm not savvy to how exactly this program works, nor do I know where to point to to help you fix it; but I didn't have any problems until 3 updates ago. IK there has been some new things added to the games code supposedly; so maybe some kind of pointer is off or maybe its out of your hands and is an SBI error? I'm not sure, but I wanted to make a report; as this tool has been invaluable to our alliance for keeping track of who has looted what; and gauging our overall performance in battle.

I appreciate all your hard work; and hope that there's a nice simple fix around the corner!

**Comment by Triky313** [comment]
The problem is outdated item lists, update the lists

New item lists, here are URLs for the settings with the updated dates!
Item list source url: https://raw.githubusercontent.com/Triky313/ao-bin-dumps/main/formatted/items.json
Item list source url: https://raw.githubusercontent.com/Triky313/ao-bin-dumps/main/items.json
mobs.json source url: https://raw.githubusercontent.com/Triky313/ao-bin-dumps/main/mobs.json 

![image](https://user-images.githubusercontent.com/14247773/221795861-f4a5458a-5bf6-49ca-a830-1feac36f87a2.png)
