### ISSUE TITLE
**App doesnt count anymore.**

### ISSUE THREAD

**Issue by Juricze** [Triky313/AlbionOnline-StatisticsAnalysis#406]
After last patch app stopped working i ac start and game folder is set corrent. Before i used this app for 2 month without problem. Reinstall didnt help, start as admin not too...
App say Unknown server "Tracking is partially active ( Please change zone ) but its doesnt help...
Windows 11.

**Comment by Triky313** [comment]
What version is the tool?

**Comment by Juricze** [comment]
v.6.3.4.26278
If i save settings with Char name Unknown server changes to West Server but also doenst count any dmg/fame nothing....

**Comment by Juricze** [comment]
also re-download and reinstall app i tried...

**Comment by Juricze** [comment]
Ok, master i find reason why this happen. Problem is because i am using VPN. I dont know where is problem but with VPN this app doesnt work. Do you have any tips what and where change to works ? I need to use VPN because my country from any time have problem with ping to Albion servers... without VPN i have unplayable ping about 300ms... with VPN 110... its mandatory for me... but you app i realy want to use too ;-)

**Comment by Triky313** [comment]
Oh yes, for that I implemented the setting on the screenshot.
The picture shows parts of the original Albion Server IP's. If you use VPN this can change, find the right ones there.
This filtering is DisplayFilters by WireShark. I don't know which VPN you use, but with ExitLag the IPs are displayed in the tool so that you can always enter the current ones.

![image](https://github.com/Triky313/AlbionOnline-StatisticsAnalysis/assets/14247773/07511f18-fa92-461d-b2e8-372da3f8d0a4)

**Comment by Juricze** [comment]
I am using ProtonVPN. problem was port forwarding... IP was same but ProtonVPN has Port forwarding like Premium function. From my side problem is solved. Thx for help.
