### ISSUE TITLE
Selling items in black market doesn't contribute to trade monitoring sell values

### ISSUE THREAD

**Issue by lewejajo9** [Triky313/AlbionOnline-StatisticsAnalysis#530]
After quickselling items in black market (not setting up a sell order, but i haven't checked if it works) their value doesn't appear in sold items in the Trade monitoring tab

1. Go to the black market and quicksell any item
2. The items' value doesn't get added

![image](https://github.com/user-attachments/assets/3fbc6a61-a054-48df-9113-5bca0a12671a)

**Comment by Triky313** [comment]
Direct sales and sales orders in the Blackmarket work without problems, please check if your tool is updated to the latest version!

**Comment by Triky313** [comment]
Direct sales and sales orders in the Blackmarket work without problems, the data is also displayed correctly.

Please check if your tool is updated to the latest version!
If this is not the case, it can sometimes be the case that if too much data is available, loading is sometimes faulty. In this case, simply change the date filter above to a different value and change it back again so that the statistics are recalculated.

Translated with DeepL.com (free version)

![grafik](https://github.com/user-attachments/assets/ba3bf3bb-0058-41cb-8d25-b39e2d9b31d4)
