### ISSUE TITLE
The total looted value shows tripled or doubled

### ISSUE THREAD

**Issue by silvasobrinho** [Triky313/AlbionOnline-StatisticsAnalysis#542]
**Describe the bug**
The total looted value is tripled or doubled

**To Reproduce**
1. Open the App
2. Start the Tracking
3. Clear a dungeon (Group or Solo)
4. looks at (total looted value)
5. the mumber isn't correct

**Expected behavior**
the total amount looted shows everything, what I looted in the dungeon correctly

**Screenshots**
![image](https://github.com/user-attachments/assets/e833ffe7-7867-493a-8659-85cd86831ac6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tool Version v7.8.1.23253
 - NPcap Version 0.9990

**Additional context**
I tested in group and solo dungeons, but the number is always wrong, when I click on the chest icon it shows all the items I got, some appear tripled and others doubled

**Comment by Triky313** [comment]
There was the problem that silver bags and the opening of silver bags counted.
From the next update, you must always open silver pouches so that they are recognized in the dungeon tracker. 

Unfortunately, there is no other solution, as I cannot distinguish between silver bags and picking up silver from the ground.
